### ISSUE TITLE
Sunnyportal2file Not Working

### ISSUE THREAD

**Issue by ShyamBhagat2004** [erijo/sunnyportal-py#12]
Hello. I am a student trying to raise more funds for solar panels in my school. To do that I will be creating a new website and app for my campus statistics on energy generated. I managed to get Sunnyportal2pvoutput to work. However it would be best if I could get Sunnyportal2file to output to a csv for me. I run the config and I get the error listed below: 

`X:\Desktop\Python\Github\sunnyportal-py>python bin/sunnyportal2file -f json config
2020-06-27 17:20:45,886 DEBUG: GET /services/authentication/100/bhaga78708%40gapps.uwcsea.edu.sg?password=<password>
2020-06-27 17:20:46,979 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="authentication" method="get" version="100" request-oid="4d8e9852-31d5-4afd-b242-8dd32c0cfce5" creation-date="6/27/2020 9:20:49 AM"><authentication identifier="44558b63-8cc4-452b-bda5-93983ec3fbdb" key="5e3e4345-18bf-467c-b933-f313eff91041">OK</authentication></service></sma.sunnyportal.services>
2020-06-27 17:20:46,998 DEBUG: GET /services/plantlist/100/44558b63-8cc4-452b-bda5-93983ec3fbdb?timestamp=2020-06-27T09%3A20%3A49&signature-method=auth&signature-version=100&signature=jmJfxlHv4jARbQ1tL%2FdNru3HH9A%3D
2020-06-27 17:20:48,144 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="plantlist" view="list" method="get" version="100" request-oid="5d8650d8-0cd5-4ce8-b9fe-396e8a928232" creation-date="6/27/2020 9:20:50 AM"><plantlist name="PV System List" count="2"><plant oid="a794c56f-8fd9-4057-95ae-69493202bca5" identifier="6b7fa900-fa14-11d4-d2d0-00014b7952d6" name="SG-UWCSEA-PoolShelter" state="unknown" /><plant oid="5e9b755f-50ba-4b65-b036-7255b5db94c4" identifier="bf2ec080-605d-11e5-191f-0001331c94e1" name="SG-UWCSEA-JrSportsHall/ArtBlk" state="unknown" /></plantlist></service></sma.sunnyportal.services>
2020-06-27 17:20:48,146 DEBUG: Extracting DataFrame from 2020-06-26 to 2020-06-26 for plant SG-UWCSEA-PoolShelter
Traceback (most recent call last):
  File "bin/sunnyportal2file", line 454, in <module>
    main()
  File "bin/sunnyportal2file", line 441, in main
    df = get_data_for_period(plant, start_date, args.end_date)
  File "bin/sunnyportal2file", line 307, in get_data_for_period
    res = get_data_for_day(plant, start_date)
  File "bin/sunnyportal2file", line 284, in get_data_for_day
    day = plant.day_overview(date, include_all=True)
TypeError: day_overview() got an unexpected keyword argument 'include_all'`

I tried to do something myself by removing the include_all keyword, I am not that experienced in Python and when I did that here is the message I got: 

`
X:\Desktop\Python\Github\sunnyportal-py>python bin/sunnyportal2file -f json config
2020-06-27 17:25:46,287 DEBUG: GET /services/authentication/100/bhaga78708%40gapps.uwcsea.edu.sg?password=<password>
2020-06-27 17:25:47,480 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="authentication" method="get" version="100" request-oid="fcea2e74-19da-4f0a-bcde-7526d9584f54" creation-date="6/27/2020 9:25:50 AM"><authentication identifier="4ad3602d-2668-4298-a0cb-8c16acf6145b" key="1b3c8ae2-fa44-4449-8ba6-523d334788e1">OK</authentication></service></sma.sunnyportal.services>
2020-06-27 17:25:47,497 DEBUG: GET /services/plantlist/100/4ad3602d-2668-4298-a0cb-8c16acf6145b?timestamp=2020-06-27T09%3A25%3A50&signature-method=auth&signature-version=100&signature=cWz7hmMyIJnQkUq37vRo23kQ%2B5g%3D
2020-06-27 17:25:48,775 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="plantlist" view="list" method="get" version="100" request-oid="53b5bb4c-0a84-4d17-a913-071a2b89b92e" creation-date="6/27/2020 9:25:51 AM"><plantlist name="PV System List" count="2"><plant oid="a794c56f-8fd9-4057-95ae-69493202bca5" identifier="6b7fa900-fa14-11d4-d2d0-00014b7952d6" name="SG-UWCSEA-PoolShelter" state="unknown" /><plant oid="5e9b755f-50ba-4b65-b036-7255b5db94c4" identifier="bf2ec080-605d-11e5-191f-0001331c94e1" name="SG-UWCSEA-JrSportsHall/ArtBlk" state="unknown" /></plantlist></service></sma.sunnyportal.services>
2020-06-27 17:25:48,777 DEBUG: Extracting DataFrame from 2020-06-26 to 2020-06-26 for plant SG-UWCSEA-PoolShelter
2020-06-27 17:25:48,789 DEBUG: GET /services/data/100/a794c56f-8fd9-4057-95ae-69493202bca5/overview-day-fifteen-total/2020-06-26?culture=en-gb&identifier=4ad3602d-2668-4298-a0cb-8c16acf6145b&timestamp=2020-06-27T09%3A25%3A51&signature-method=auth&signature-version=100&signature=Inl0nvymJVx6l5MET929JsYsnRA%3D
2020-06-27 17:25:50,045 DEBUG: Response: <?xml version="1.0" encoding="UTF-8"?><sma.sunnyportal.services>
  <service name="data" method="get" version="100" request-oid="290910bd-e9fa-43f2-86c0-76511b213a87" creation-date="6/27/2020 9:25:52 AM">
    <data>
      <overview-day-fifteen-total>
        <channel name="Power" meta-name="Power" unit="kW">
          <day timestamp="26/06/2020">
            <fiveteen timestamp="00:15" />
            <fiveteen timestamp="00:30" />
            <fiveteen timestamp="00:45" />
            <fiveteen timestamp="01:00" />
            <fiveteen timestamp="01:15" />
            <fiveteen timestamp="01:30" />
            <fiveteen timestamp="01:45" />
            <fiveteen timestamp="02:00" />
            <fiveteen timestamp="02:15" />
            <fiveteen timestamp="02:30" />
            <fiveteen timestamp="02:45" />
            <fiveteen timestamp="03:00" />
            <fiveteen timestamp="03:15" />
            <fiveteen timestamp="03:30" />
            <fiveteen timestamp="03:45" />
            <fiveteen timestamp="04:00" />
            <fiveteen timestamp="04:15" />
            <fiveteen timestamp="04:30" />
            <fiveteen timestamp="04:45" />
            <fiveteen timestamp="05:00" />
            <fiveteen timestamp="05:15" />
            <fiveteen timestamp="05:30" />
            <fiveteen timestamp="05:45" />
            <fiveteen timestamp="06:00" />
            <fiveteen timestamp="06:15" />
            <fiveteen timestamp="06:30" />
            <fiveteen timestamp="06:45" />
            <fiveteen timestamp="07:00" />
            <fiveteen timestamp="07:15" min="0" max="0" mean="0" />
            <fiveteen timestamp="07:30" min="0.026" max="0.142" mean="0.081" />
            <fiveteen timestamp="07:45" min="0.227" max="0.344" mean="0.287" />
            <fiveteen timestamp="08:00" min="0.432" max="0.554" mean="0.496" />
            <fiveteen timestamp="08:15" min="0.623" max="0.801" mean="0.71" />
            <fiveteen timestamp="08:30" min="0.923" max="1.176" mean="1.049" />
            <fiveteen timestamp="08:45" min="1.257" max="1.451" mean="1.347" />
            <fiveteen timestamp="09:00" min="1.563" max="1.716" mean="1.632" />
            <fiveteen timestamp="09:15" min="1.83" max="1.919" mean="1.885" />
            <fiveteen timestamp="09:30" min="1.93" max="2.387" mean="2.143" />
            <fiveteen timestamp="09:45" min="2.434" max="2.665" mean="2.552" />
            <fiveteen timestamp="10:00" min="2.798" max="2.906" mean="2.838" />
            <fiveteen timestamp="10:15" min="2.602" max="2.94" mean="2.752" />
            <fiveteen timestamp="10:30" min="3.013" max="3.244" mean="3.126" />
            <fiveteen timestamp="10:45" min="3.226" max="4.708" mean="4.047" />
            <fiveteen timestamp="11:00" min="5.76" max="6.159" mean="5.914" />
            <fiveteen timestamp="11:15" min="4.395" max="6.5" mean="5.204" />
            <fiveteen timestamp="11:30" min="3.112" max="4.858" mean="4.023" />
            <fiveteen timestamp="11:45" min="4.414" max="7.934" mean="6.195" />
            <fiveteen timestamp="12:00" min="4.131" max="5.519" mean="4.984" />
            <fiveteen timestamp="12:15" min="4.317" max="8.655" mean="7.012" />
            <fiveteen timestamp="12:30" min="6.809" max="10.067" mean="8.932" />
            <fiveteen timestamp="12:45" min="9.883" max="10.192" mean="10.009" />
            <fiveteen timestamp="13:00" min="6.91" max="8.739" mean="7.609" />
            <fiveteen timestamp="13:15" min="2.815" max="4.975" mean="3.902" />
            <fiveteen timestamp="13:30" min="6.842" max="10.46" mean="9.155" />
            <fiveteen timestamp="13:45" min="8.179" max="10" mean="9.152" />
            <fiveteen timestamp="14:00" min="10.201" max="11.105" mean="10.686" />
            <fiveteen timestamp="14:15" min="4.252" max="11.28" mean="7.048" />
            <fiveteen timestamp="14:30" min="6.7" max="9.738" mean="7.833" />
            <fiveteen timestamp="14:45" min="2.756" max="5.693" mean="4.248" />
            <fiveteen timestamp="15:00" min="1.349" max="4.258" mean="2.619" />
            <fiveteen timestamp="15:15" min="1.485" max="3.828" mean="2.317" />
            <fiveteen timestamp="15:30" min="2.022" max="4.162" mean="3.4" />
            <fiveteen timestamp="15:45" min="2.077" max="5.088" mean="3.124" />
            <fiveteen timestamp="16:00" min="3.72" max="6.227" mean="4.94" />
            <fiveteen timestamp="16:15" min="1.665" max="2" mean="1.779" />
            <fiveteen timestamp="16:30" min="1.857" max="3.343" mean="2.592" />
            <fiveteen timestamp="16:45" min="1.88" max="2.451" mean="2.237" />
            <fiveteen timestamp="17:00" min="2.518" max="3.511" mean="2.895" />
            <fiveteen timestamp="17:15" min="1.393" max="2.893" mean="2.093" />
            <fiveteen timestamp="17:30" min="1.178" max="1.353" mean="1.248" />
            <fiveteen timestamp="17:45" min="0.961" max="1.079" mean="1.034" />
            <fiveteen timestamp="18:00" min="0.845" max="0.861" mean="0.853" />
            <fiveteen timestamp="18:15" min="0.616" max="0.821" mean="0.713" />
            <fiveteen timestamp="18:30" min="0.311" max="0.494" mean="0.394" />
            <fiveteen timestamp="18:45" min="0.274" max="0.304" mean="0.294" />
            <fiveteen timestamp="19:00" min="0.025" max="0.181" mean="0.096" />
            <fiveteen timestamp="19:15" min="0" max="0.005" mean="0.002" />
            <fiveteen timestamp="19:30" min="0" max="0" mean="0" />
            <fiveteen timestamp="19:45" />
            <fiveteen timestamp="20:00" />
            <fiveteen timestamp="20:15" />
            <fiveteen timestamp="20:30" />
            <fiveteen timestamp="20:45" />
            <fiveteen timestamp="21:00" />
            <fiveteen timestamp="21:15" />
            <fiveteen timestamp="21:30" />
            <fiveteen timestamp="21:45" />
            <fiveteen timestamp="22:00" />
            <fiveteen timestamp="22:15" />
            <fiveteen timestamp="22:30" />
            <fiveteen timestamp="22:45" />
            <fiveteen timestamp="23:00" />
            <fiveteen timestamp="23:15" />
            <fiveteen timestamp="23:30" />
            <fiveteen timestamp="23:45" />
            <fiveteen timestamp="00:00" />
          </day>
        </channel>
        <channel name="Total yield" meta-name="Energy" unit="kWh">
          <day timestamp="26/06/2020" absolute="86961.907" difference="42.403" />
        </channel>
      </overview-day-fifteen-total>
    </data>
  </service>
</sma.sunnyportal.services>
Traceback (most recent call last):
  File "bin/sunnyportal2file", line 454, in <module>
    main()
  File "bin/sunnyportal2file", line 441, in main
    df = get_data_for_period(plant, start_date, args.end_date)
  File "bin/sunnyportal2file", line 311, in get_data_for_period
    min_power.append(power_measurement.min)
AttributeError: 'Power' object has no attribute 'min'`

Would you please be able to assist me in fixing this issue? Thank you very much.

**Comment by joebe975** [comment]
Why do you specify json as output format if you want csv?

Have you tried following the exact steps from the [README.md](https://github.com/erijo/sunnyportal-py/blob/master/README.md) with a clean copy of the repo?

**Comment by ShyamBhagat2004** [comment]
Hello. Yes, I tried csv first, got the same error message. Also, a clean
repo clone didn't seem to fix the problem.

**Comment by ShyamBhagat2004** [comment]
Sorry forgot to mention, I did try to follow the README instructions
exactly as it was written. Does sunnyportal2file work on your machine? That
could possibly be the problem.

Thanks and regards :)

**Comment by ShyamBhagat2004** [comment]
As in, maybe by machine is missing some dependencies.

**Comment by joebe975** [comment]
From the error message it sounds like you are using an older version of [client.py](https://github.com/erijo/sunnyportal-py/blob/master/sunnyportal/client.py), as the keyword argument "include_all" was added relatively recently. What do you see in line 93 in your client.py? Don't you see include_all in the function definition? Try removing the keyword argument include_all from line 284 in [weather2file](https://github.com/erijo/sunnyportal-py/blob/master/bin/sunnyportal2file) and add some print or logging.debug in the day_overview function definition (client.py) to confirm whether it uses the function you think it's using.

Yes, it works on my machine with Ubuntu 20.04.

**Comment by ShyamBhagat2004** [comment]
Hi, let me start off by saying thank you for assisting me, it is kind and
generous of you. I’m 16 right now and have just self-taught myself Python
during quarantine, and you have been the nicest person online. Let me tell
you what I tried:
Just to make it easier, I have uploaded the current folder of my
sunnyportal-py folder. (the password in the config file is only used for
sunnyportal, so it is ok)

From the error message it sounds like you are using an older version of
client.py, as the keyword argument "include_all" was added relatively
recently. What do you see in line 93 in your client.py? Don't you see
include_all in the function definition? Try removing the keyword argument
include_all from line 284 in weather2file and add some print or
logging.debug in the day_overview function definition (client.py) to
confirm whether it uses the function you think it's using.

In client.py, line 93 I see
def day_overview(self, date, quarter=True, include_all=False):

In sunnyportal2file, here are lines 283, 284, and 285:
def get_data_for_day(plant, date):
    day = plant.day_overview(date, include_all=True)
    return day.power_measurements

As per your instructions, I removed include_all = True from Line 284 and
got this as a response:


Do you have any idea what I could do to fix this? Maybe if your version of
the files in sunnyportal-py folder are different on your machine and you
could send those over?
Thank you and regards
