### ISSUE TITLE
sunnyportal errors

### ISSUE THREAD

**Issue by halfagascan** [erijo/sunnyportal-py#25]
new program installed via git.
PYTHONPATH=. ./bin/sunnyportal2pvoutput /home/jerry/programs/sunnyportal-py/sunnyportal.config -p 2 -o
errors:
2021-10-02 12:35:43,951 DEBUG: POST to /service/r2/addoutput.jsp: {'data': '20211001,15826,,,2728,10:15'}
2021-10-02 12:35:44,021 DEBUG: HTTP response: 400 (Bad Request): Bad request 400: Peak time [2728] invalid on 20211001
2021-10-02 12:35:44,021 DEBUG: POST to /service/r2/addoutput.jsp: {'data': '20211001,15826,,,2728,10:15'}
2021-10-02 12:35:44,091 DEBUG: HTTP response: 400 (Bad Request): Bad request 400: Peak time [2728] invalid on 20211001
2021-10-02 12:35:44,091 ERROR: Failed to add output batch: Bad request 400: Peak time [2728] invalid on 20211001
Traceback (most recent call last):
  File "/home/jerry/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 284, in <module>
    main()
  File "/home/jerry/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 278, in main
    pvoutput.add_batch_output(data)
  File "/home/jerry/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 122, in add_batch_output
    raise Exception("could not add output batch")
Exception: could not add output batch

I am having issues with the inverter, its not wanting to display some days generation from the web, the installer says its all fine, yea right.
thanks

**Comment by erijo** [comment]
I failed to update the field order after switching to addoutput from addbatchoutput. Should be fixed now. Please try again.

**Comment by halfagascan** [comment]
fixed now, thanks
