### ISSUE TITLE
Something Change?

### ISSUE THREAD

**Issue by halfagascan** [erijo/sunnyportal-py#26]
Just tried the script, seems some has changed, the script completes, but no data returned.
```XXX@deb:~/programs/sunnyportal-py$ PYTHONPATH=. ./bin/sunnyportal2pvoutput /home/XXX/programs/sunnyportal-py/sunnyportal.config -p 2
2021-10-29 06:54:19,439 DEBUG: GET /services/authentication/100/XXX.XXX%40xxxx.com?password=<password>
2021-10-29 06:54:20,084 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="authentication" method="get" version="100" request-oid="2333103e-08ac-4f9a-a5fb-e11861df94d2" creation-date="10/29/2021 11:54:20 AM"><authentication identifier="15xxxaea-xxxx-4ffb-xxx-c0xxxxxxxx" key="xxxx-b447-xxxx-a855-xxxx">OK</authentication></service></sma.sunnyportal.services>
2021-10-29 06:54:20,088 DEBUG: GET /services/plantlist/100/15xxxaea-xxxx-4ffb-xxx-c0xxxxxxxx?timestamp=2021-10-29T11%3A54%3A20&signature-method=auth&signature-version=100&signature=xxxx%3D
2021-10-29 06:54:20,748 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="plantlist" view="list" method="get" version="100" request-oid="a0b05068-f6a0-4f95-8032-db84df9a7ff6" creation-date="10/29/2021 11:54:20 AM"><plantlist name="PV System List" count="1"><plant oid="xxxxd36cf84bcddb" identifier="adad16ec-a18b-403d-903d-37ebe141228d" name="xxxx xxx" state="unknown" /></plantlist></service></sma.sunnyportal.services>
2021-10-29 06:54:20,750 DEBUG: DELETE /services/authentication/100/15xxxaea-xxxx-4ffb-xxx-c0xxxxxxxx?timestamp=2021-10-29T11%3A54%3A20&signature-method=auth&signature-version=100&signature=xxxx xxx
2021-10-29 06:54:21,395 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="authentication" method="delete" version="100" request-oid="xxxx xxx" creation-date="10/29/2021 11:54:21 AM"><authentication identifier="15xxxaea-xxxx-4ffb-xxx-c0xxxxxxxx">OK</authentication></service></sma.sunnyportal.services>```
Running:
```PYTHONPATH=. ./bin/sunnyportal2file sunnyportal.config --format csv``` works fine, I am able to see:```<fiveteen timestamp="08:15" mean="0.104" />
            <fiveteen timestamp="08:30" mean="0.336" />
            <fiveteen timestamp="08:45" mean="0.424" />
            <fiveteen timestamp="09:00" mean="0.456" />
            <fiveteen timestamp="09:15" mean="0.42" />
            <fiveteen timestamp="09:30" mean="0.752" />
            <fiveteen timestamp="09:45" mean="1.604" />
            <fiveteen timestamp="10:00" mean="2.38" />
            <fiveteen timestamp="10:15" mean="2.324" />
            <fiveteen timestamp="10:30" mean="2.096" />
            <fiveteen timestamp="10:45" mean="2.808" />
            <fiveteen timestamp="11:00" mean="3.444" />
            <fiveteen timestamp="11:15" mean="3.644" />
            <fiveteen timestamp="11:30" mean="3.812" />
            <fiveteen timestamp="11:45" mean="3.96" />
            <fiveteen timestamp="12:00" mean="4.076" />
            <fiveteen timestamp="12:15" mean="4.152" />
            <fiveteen timestamp="12:30" mean="4.132" />
            <fiveteen timestamp="12:45" mean="3.448" />
            <fiveteen timestamp="13:00" mean="4.372" />
            <fiveteen timestamp="13:15" mean="4.36" />
            <fiveteen timestamp="13:30" mean="4.32" />
            <fiveteen timestamp="13:45" mean="4.224" />```
and the file gets created```-rw-r--r--  1 me me  6615 Oct 29 07:05 'me.csv'```
Any advice?
Thanks

**Comment by joebe975** [comment]
I don't understand the issue. You ran the script and a csv-file with data was created. What is the problem?

Since you did not specify the start nor end date, it will default to yesterday which means that you only get one day of data. Have you read the README?

**Comment by halfagascan** [comment]
Sorry, forgot to include the line I ran.
The issue:
```PYTHONPATH=. ./bin/sunnyportal2pvoutput /home/me/programs/sunnyportal-py/sunnyportal.config -p 1```
yields NO OUTPUT, no data uploaded to pvoutput, no errors
This works FINE:```PYTHONPATH=. ./bin/sunnyportal2file sunnyportal.config --format csv```
The csv file gets created and does have info.

**Comment by erijo** [comment]
First make sure that you don't have any local modifications to the script. If you don't, could you add debug traces (e.g. `print("here")`) to the script to see how far it gets?

**Comment by halfagascan** [comment]
ok, not sure what changed on my end.
Here's what I tried:
```PYTHONPATH=. ./bin/sunnyportal2pvoutput sunnyportal.config -c -o```
results in error:
```<data>
      <overview-day-fifteen-total>
        <channel name="Power" meta-name="Power" unit="kW">
          <day timestamp="30/10/2021">
            
      <overview-day-fifteen-total>
        <channel name="Power" meta-name="Power" unit="kW">
          <day timestamp="30/10/2021">
            <fiveteen timestamp="00:15" mean="0" />
            
            <fiveteen timestamp="08:15" mean="0" />
            <fiveteen timestamp="08:30" mean="0.032" />
            <fiveteen timestamp="08:45" mean="0.128" />
            <fiveteen timestamp="09:00" mean="0.284" />
            <fiveteen timestamp="09:15" mean="0.504" />
            <fiveteen timestamp="09:30" mean="0.932" />
            <fiveteen timestamp="09:45" mean="1.404" />
            <fiveteen timestamp="10:00" mean="0.912" />
            <fiveteen timestamp="10:15" mean="2.548" />
            <fiveteen timestamp="10:30" mean="1.152" />
            <fiveteen timestamp="10:45" />
  
<channel name="Total yield" meta-name="Energy" unit="kWh">
          <day timestamp="30/10/2021" absolute="8606.009" difference="1.973" />
        </channel>
      </overview-day-fifteen-total>
    </data>
  </service>
</sma.sunnyportal.services>


Traceback (most recent call last):
  File "/home/me/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 283, in <module>
    main()
  File "/home/me/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 274, in main
    data = get_data_for_period(
  File "/home/me/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 161, in get_data_for_period
    res = get_data_for_day(plant, start_date, get_consumption)
  File "/home/me/programs/sunnyportal-py/./bin/sunnyportal2pvoutput", line 144, in get_data_for_day
    balance = plant.day_energy_balance(date).day
  File "/home/me/programs/sunnyportal-py/sunnyportal/client.py", line 123, in day_energy_balance
    return self.client.do_request(req)
  File "/home/me/programs/sunnyportal-py/sunnyportal/client.py", line 46, in do_request
    return request.perform(conn)
  File "/home/me/programs/sunnyportal-py/sunnyportal/requests.py", line 84, in perform
    return self.handle_response(data)
  File "/home/me/programs/sunnyportal-py/sunnyportal/requests.py", line 241, in handle_response
    return responses.EnergyBalanceResponse(data)
  File "/home/me/programs/sunnyportal-py/sunnyportal/responses.py", line 61, in __init__
    self.parse(data)
  File "/home/me/programs/sunnyportal-py/sunnyportal/responses.py", line 353, in parse
    tag = super().parse(data)
  File "/home/me/programs/sunnyportal-py/sunnyportal/responses.py", line 103, in parse
    raise ResponseError(msg, error.findtext("code"))
sunnyportal.responses.ResponseError: bad-request: Error in processing request. | The feature EnergyBilance is not possible or active for the plant 123456789```

I've grepped for "EnergyBilance" in sunnyportal.respones, no such luck.
This is on debian, ```Linux deb 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux```
For this one, I'll refetch the code

If I run:
```PYTHONPATH=. ./bin/sunnyportal2pvoutput sunnyportal.config -o```
on ```archlinux, Linux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux```
no such error, and it appears to upload the data to pvoutput

I have no modifications to any script, a suggestion on where to place ```print("here")``` for debugging?
thanks

**Comment by halfagascan** [comment]
well, seems a git clone solved the issue, no errors.
I'll check again later today to see if the pvoutput site updates.
thanks

**Comment by erijo** [comment]
In the first case you used `-c` to get consumption, in the second you didn't. It seems like your system doesn't support reporting consumption. Can you see this in sunnyportal?

The error you get is returned from sunnyportal and isn't something that this python module creates. But it should have been logged as a response before the exception. I don't really understand why it wasn't in this case.

**Comment by halfagascan** [comment]
Not really sure what happened, a reinstall seems to have fixed the issue.
A clean install on the archlinux box had no issues, this debian box does do some weird shit, I sit on a discord server, and sometimes copy/paste ends up in discord, sometimes it starts inputting characters instead of letters/numbers.
Anyway the issue is resolved, thanks for the help.

-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Oct 31, 2021, 12:56 by ***@***.***:
