### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by SaSha-ShaS** [erijo/sunnyportal-py#29]
Hello Erik,

I was searching for a way to get the data of my PV plant downloaded from the SMA Sunny Portal. I found your repository here on Github and started to try. I followed the readme and set up the path. This seems to work properly:

```
(actual) c:\sunnyportal-py>python bin\sunnyportal2file -h
usage: sunnyportal2file [-h] -f {json,csv,pickle,feather,parquet,excel,sqlite} [-s START_DATE] [-e END_DATE] [-i INCLUDE_FILTER] [-q] config

Save information from Sunny Portal to file

positional arguments:
  config                Configuration file to use

optional arguments:
  -h, --help            show this help message and exit
  -f {json,csv,pickle,feather,parquet,excel,sqlite}, --format {json,csv,pickle,feather,parquet,excel,sqlite}
                        Format for which the data is to be saved
  -s START_DATE, --start-date START_DATE
                        The start date of data to be saved in the format YYYY-MM-DD (default yesterday)
  -e END_DATE, --end-date END_DATE
                        The end date of data to be saved in the format YYYY-MM-DD (default yesterday)
  -i INCLUDE_FILTER, --include-filter INCLUDE_FILTER
                        A string used to filter which plants to include (default includes all plants)
  -q, --quiet           Silence output
```

But when executing sunnyportal2file I end up in the following error message:

```
(actual) c:\sunnyportal-py>python bin\sunnyportal2file sunnyportal.config --format csv
2021-12-19 21:27:52,625 DEBUG: GET /services/authentication/100/xxx%40yyy.com?password=<password>
Traceback (most recent call last):
  File "c:\sunnyportal-py\bin\sunnyportal2file", line 428, in <module>
    main()
  File "c:\sunnyportal-py\bin\sunnyportal2file", line 404, in main   
    for plant in client.get_plants():
  File "c:\sunnyportal-py\sunnyportal\client.py", line 64, in get_plants
    req = requests.PlantListRequest(self.get_token())
  File "c:\sunnyportal-py\sunnyportal\client.py", line 53, in get_token
    self.token = self.do_request(req)
  File "c:\sunnyportal-py\sunnyportal\client.py", line 48, in do_request
    return request.perform(conn)
  File "c:\sunnyportal-py\sunnyportal\requests.py", line 73, in perform
    connection.request(self.method, self.url)
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\Sascha\.conda\envs\actual\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Sascha\.conda\envs\actual\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Sascha\.conda\envs\actual\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Sascha\.conda\envs\actual\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
```

Do you have any idea?

Thank you in advance.

**Comment by erijo** [comment]
Looks like a problem with your environment. You'll have to find ways to debug the ssl environment. Not something that I can help with unfortunately.
