### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by petepall** [erijo/sunnyportal-py#33]
Hi All,

I'm new to this and have an issue when trying to run the PYTHONPATH=. ./bin/sunnyportal2pvoutput --dry-run sunnyportal.config command.

The following error stack is returned.
2022-09-23 12:30:44,125 DEBUG: GET /services/authentication/100/<my email>?password=<password>
Traceback (most recent call last):
  File "/Users/peter/Dev/sunnyportal-py/./bin/sunnyportal2pvoutput", line 284, in <module>
    main()
  File "/Users/peter/Dev/sunnyportal-py/./bin/sunnyportal2pvoutput", line 228, in main
    plants = client.get_plants()
  File "/Users/peter/Dev/sunnyportal-py/sunnyportal/client.py", line 62, in get_plants
    req = requests.PlantListRequest(self.get_token())
  File "/Users/peter/Dev/sunnyportal-py/sunnyportal/client.py", line 51, in get_token
    self.token = self.do_request(req)
  File "/Users/peter/Dev/sunnyportal-py/sunnyportal/client.py", line 46, in do_request
    return request.perform(conn)
  File "/Users/peter/Dev/sunnyportal-py/sunnyportal/requests.py", line 73, in perform
    connection.request(self.method, self.url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

Any pointers on why I'm getting the SSL certificate failed error?

**Comment by petepall** [comment]
I ran the following command to resolve the certificate issue.
/Applications/Python\ 3.10/Install\ Certificates.command
