### ISSUE TITLE
Problem when I call plant.profile()

### ISSUE THREAD

**Issue by DOUADYtom** [erijo/sunnyportal-py#8]
Hi,
I just want to have the power_peak of all my plants and so I tried this:

` for plant in client.get_plants():  
        plant.profile().peak_power
    client.logout()`

and the result in the terminal is : 
`Traceback (most recent call last):
  File "c:\Users\Desktop\Stage\python\test3.py", line 57, in <module>
    main()
  File "c:\Users\Desktop\Stage\python\test3.py", line 46, in main
    plant.profile().peak_power
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\client.py", line 77, in profile
    return self.client.do_request(req)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\client.py", line 45, in do_request
    return request.perform(conn)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\requests.py", line 82, in perform
    return self.handle_response(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\requests.py", line 131, in handle_response
    return responses.PlantProfileResponse(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\responses.py", line 53, in __init__
    self.parse(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\responses.py", line 155, in parse
    for channel in tag.find('production-data').findall('channel'):
AttributeError: 'NoneType' object has no attribute 'findall'`

I just don't understand why this error appears when I happen to have plant.name correctly and even plant.day_overview ().difference correctly too. 

Thanks, Tom.

**Comment by DOUADYtom** [comment]
I think I have partially solved the problem.
I simply commented the code inside "responses.py":

`# self.production_data = {}`
`# for channel in tag.find('production-data').findall('channel'):`
`#     self.production_data[channel.attrib['meta-name']] = channel.text`

**Comment by joebe975** [comment]
Your code snippet would have resulted in SyntaxError, so it cannot be what you ran. Furthermore, the error occurred in test3.py which I suppose is your test script, which you haven't shared, so I suppose the issue you have opened is not related to the master branch but rather to some local testing?

**Comment by erijo** [comment]
Could you please add the following to your test script, reproduce the error and post the output?
```py
import logging
...
logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.DEBUG)
```

**Comment by DOUADYtom** [comment]
> 
> 
> Your code snippet would have resulted in SyntaxError, so it cannot be what you ran. Furthermore, the error occurred in test3.py which I suppose is your test script, which you haven't shared, so I suppose the issue you have opened is not related to the master branch but rather to some local testing?

that's right these are things related to local tests

**Comment by DOUADYtom** [comment]
> 
> 
> Could you please add the following to your test script, reproduce the error and post the output?
> 
> ```python
> import logging
> ...
> logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.DEBUG)
> ```

My test code is :

```
#!/usr/bin/env python3

from datetime import date, timedelta
from getpass import getpass

import configparser
import logging
import sys
import sunnyportal.client

def main():

    today = date.today()
    yesterday = today - timedelta(days=1)

    logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s',
                        level=logging.DEBUG)

    if len(sys.argv) != 3:
        print("Usage: %s <config>" % sys.argv[0])
        sys.exit(1)

    section = 'sunnyportal'
    config = configparser.ConfigParser()
    config[section] = {}
    config.read(sys.argv[1])

    if not config[section].get('email'):
        config[section]['email'] = input("E-mail: ")
    if not config[section].get('password'):
        config[section]['password'] = getpass()

    with open(sys.argv[1], 'w') as f:
        config.write(f)

    client = sunnyportal.client.Client(
        config[section]['email'], config[section]['password'])

    with open(sys.argv[2], "r") as f2:
        f2.read()
    with open(sys.argv[2], "w") as f2:
        f2.write("")
    f2.close()

    for plant in client.get_plants():
        strData = plant.name + '\t' + str(plant.profile().peak_power) + '\t' + str(plant.day_overview(yesterday).difference) + '\n'
        with open(sys.argv[2], 'a') as f2:
            f2.write(strData)
        f2.close()
        
        # plant.name
        # plant.profile()
        # plant.last_data_exact(date.today())
        # plant.all_data('year')
        # plant.all_data('month')
        # plant.month_overview(date(2016, 1, 1))
        # plant.year_overview(date(2016, 2, 1))
    client.logout()

if __name__ == '__main__':
    main()
```

I just write response in an other file for the moment. 
(the file is an argument passed when calling the script)

**Comment by DOUADYtom** [comment]
if I do not comment on the following lines, I encounter the problem that I noted at the very beginning.
```
#  self.production_data = {}
# for channel in tag.find('production-data').findall('channel'):
# self.production_data[channel.attrib['meta-name']] = channel.text
```

**Comment by erijo** [comment]
But isn't there some more output before the error? There should be debug logs from the communication.

**Comment by DOUADYtom** [comment]
For the code I just give you yesterday I got this in my terminal. I just want to notice that this same script works if I comment out what is looking for channels in reponse.py
```
PS C:\Users\Desktop\Stage\python> python c:\Users\Desktop\Stage\python\test3.py .\config.txt .\data.txt
2020-04-22 08:25:29,867 DEBUG: GET /services/authentication/100/maintenance%40o-sitoit.com?password=<password>
2020-04-22 08:25:30,172 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="authentication"
method="get" version="100" request-oid="" creation-date="4/22/2020 6:25:32 AM"><authentication identifier="27739" key="650b8f95-181a-4d88-bc56-eded61cd8d2f">OK</authentication></service></sma.sunnyportal.services>
2020-04-22 08:25:30,220 DEBUG: GET /services/plantlist/100/2791bc0e-33f0-4665-9f56-988a8b33e739?timestamp=2020-04-22T06%3A25%3A32&signature-method=auth&signature-version=100&signature=cC4Gwdw9abdhI0NXlSvBWBaQI34%3D
2020-04-22 08:25:30,736 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="plantlist" view="list" method="get" version="100" request-oid="" creation-date="4/22/2020 6:25:32 AM"><plantlist name="PV System List" count="31"><plant oid="" identifier="f7bd48533e7" name="VIOLLET BOSSON Gilbert" state="unknown" /><plant oid="" identifier="09993b59a293594c" name="BOC04" state="unknown" /><plant oid="" identifier="" name="MAIG01" state="unknown" /><plant oid="" identifier="" name="TER03" state="unknown" /><plant oid="" identifier="" name="GFON01" state="unknown" /><plant oid="" identifier="" name="EPPAD
71 DUTERTE" state="unknown" /><plant oid="" identifier="" name="MARN01" state="unknown" /><plant oid="" identifier="" name="Becourt 01" state="unknown" /><plant oid="" identifier="" name="GAEC DE PLAINE" state="unknown" /><plant oid="" identifier="" name="FEVRE MASTER" state="unknown" /><plant oid="" identifier="" name="DE VILLELE" state="unknown" /><plant oid="" identifier="" name="FON01" state="unknown" /><plant oid="" identifier="" name="SER01" state="unknown" /><plant oid="" identifier="" name="CLU01" state="unknown" /><plant oid="" identifier="" name="GUY01" state="unknown" /><plant oid="" identifier="" name="BOC03" state="unknown" /><plant oid="" identifier="" name="FEV01" state="unknown"
/><plant oid="" identifier="" name="BONN01" state="unknown" /><plant oid="" identifier="" name="TRAPET" state="unknown" /><plant oid="" identifier="" name="BFE02" state="unknown" /><plant oid="" identifier="" name="SER02" state="unknown" /><plant oid="" identifier="c" name="bac01" state="unknown" /><plant oid="b443" identifier="09d5ef0e-733891" name="BFE04" state="unknown" /><plant oid="ec86a728" identifier="5f1-ed1d876e7883" name="GFON02" state="unknown" /><plant oid="34be5ff31e" identifier="c6dde4f5-b125c-5908" name="BFE05" state="unknown" /><plant oid="20b789" identifier="564c848" name="MET01" state="unknown" /><plant oid="9cc041f" identifier="c1ed85cc2df2616e" name="MARC01" state="unknown" /><plant oid="9f27f14f" identifier="f2442e" name="BUE01" state="unknown" /><plant oid="82d78" identifier="90abef" name="BFE13" state="unknown" /><plant oid="ea12cb" identifier="50c298-c8f1c42bf8fc" name="MOU01" state="unknown" /><plant oid="c839c4f" identifier="540757" name="VIO02" state="unknown" /></plantlist></service></sma.sunnyportal.services>
2020-04-22 08:25:30,792 DEBUG: GET /services/plant/100/0fcd88b6-e60c-467b-82cd-0a7b652fdd2d?view=profile&culture=en-gb&plant-image-size=64px&identifier=2733e739&timestamp=2020-04-22T06%3A25%3A32&signature-method=auth&signature-version=100&signature=ud6bLlRmwXLkH3dWjAlI4Pc8yZM%3D
2020-04-22 08:25:31,130 DEBUG: Response: <?xml version="1.0" encoding="utf-8"?><sma.sunnyportal.services><service name="plant" view="profile" method="get" version="100" request-oid="d50f547b" creation-date="4/22/2020 6:25:33 AM"><plant p3:type="PlantProfile" name="PV System Profile" xmlns:p3="http://www.w3.org/2001/XMLSchema-instance"><name name="PV System Name">VIOLLET BOSSON
Gilbert</name><peak-power name="PV system power" unit="kWp">2.6</peak-power><city-country name="Location">Marignier, France</city-country><start-date name="Commissioning">13/12/2019</start-date><inverters name="Inverter"><inverter count="1" deviceIcon="https://com.sunny-portal.de/services/images/100/455/PIC_16">Sunny Boy 2.5 1VL-40</inverter></inverters><communicationProducts name="Communication"><communicationProduct count="1" deviceIcon="https://com.sunny-portal.de/services/images/100/455/PIC_16">SMA Webconnect</communicationProduct></communicationProducts></plant></service></sma.sunnyportal.services>
Traceback (most recent call last):
  File "c:\Users\Desktop\Stage\python\test3.py", line 61, in <module>
    main()
  File "c:\Users\Desktop\Stage\python\test3.py", line 46, in main
    strData = plant.name + '\t' + str(plant.profile().peak_power) + '\t' + str(plant.day_overview(yesterday).difference) + '\n'
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\client.py", line 77, in profile
    return self.client.do_request(req)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\client.py", line 45, in do_request
    return request.perform(conn)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\requests.py", line 82, in perform
    return self.handle_response(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\requests.py", line 131, in handle_response
    return responses.PlantProfileResponse(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\responses.py", line 53, in __init__
    self.parse(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sunnyportal\responses.py", line 155, in parse
    for channel in tag.find('production-data').findall('channel'):
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by erijo** [comment]
Should be fixed now. Please try with latest master.

**Comment by DOUADYtom** [comment]
> 
> 
> Should be fixed now. Please try with latest master.

Thanks for all !
